### ISSUE TITLE
Coloring is broken on windows *11* command prompt and powershell with a recent update.

### ISSUE THREAD

**Issue by stephencomputer** [haxiomic/haxe-script-utils#12]
Attempting to color stdout will cause the ansi codes to show up and not the actual color, here is an example:
![Screenshot 2022-10-29 161032](https://user-images.githubusercontent.com/90519370/198850784-5b829d9a-ebc2-4646-af8c-1fdc791093c5.png)

I have no idea if this is a windows issue or if it is able to be fixed by you, but if it is able to be fixed, I think it should be.

**Comment by stephencomputer** [comment]
fixed with the latest windows update

**Comment by haxiomic** [comment]
Great news, thanks for the update!

**Comment by varadig** [comment]
No, it's not.
![image](https://user-images.githubusercontent.com/6317148/236991240-3d101399-f343-4ea8-ae44-3df495134b47.png)
![image](https://user-images.githubusercontent.com/6317148/236991456-412cdaa2-06bc-4507-8f55-cd71fa476224.png)

**Comment by haxiomic** [comment]
This is an interesting bug! Can you share the code to reproduce?

I’ve been testing on windows 10 without issues but not windows 11, which are you running?
