### ISSUE TITLE
Requires haxe 4.0 compiler

### ISSUE THREAD

**Issue by claus-d3y** [haxiomic/haxe-script-utils#6]
This issue will hopefully resolve itself soon, when the world moves on to a better place, and we all have haxe 4.0 to run our stuff, but until then:
**This project, which looks very nice, will not compile with haxe 3.4.7**

Just thought it could help somebody else, who like me is forced not to live on the edge ;)

**Comment by haxiomic** [comment]
Thanks for pointing that out, I’ll make it clear in the readme :)

**Comment by haxiomic** [comment]
Made some tweaks to support haxe 3, tested with haxe 3.2.1, 3.4.4 and 3.4.7

Haxelib version has been updated and is now [0.2.10](https://lib.haxe.org/p/Console.hx/0.2.10/)

**Comment by claus-d3y** [comment]
Thanks so much for the fix! My output is now looking awesome!
