### ISSUE TITLE
Escaping does not seem to work

### ISSUE THREAD

**Issue by claus-d3y** [haxiomic/haxe-script-utils#9]
When I try the following:
`Console.log('testing esc: \\<b>not\\<//> so <b>bold<//>')`
I get: testing esc: \\**not**\\ so **bold**

Yes, I have cheated to get this post to look right. It is a pain to discuss errors regarding formatting ;)

**Comment by haxiomic** [comment]
Thanks for reporting @cld-laerdal, just pushed a change – could you see if it works now?

**Comment by claus-d3y** [comment]
Thanks for the *very* prompt fix.

It opens, however, the annoying issue of escaping the escape character:
`		Console.log('\\<red> not red\\\\<b>but bold\\\\\\<green>, yet no green');
`
yields: \<red>not red \\\<blue>but bold\\\\\<green>, yet no green
rather than probably: \<red>not red \\<b>but bold*\\\\\<green>, yet no green</b>

The fix seems to be a bit complicated since you might easily detect the situation, but have to add a whole new category of changes to get the number of \\'s right...

Perhaps a more viable solution would be to replace the \ with a *literal* flag, something like
 `		Console.log('<literal><red> not red\\<b>but bold\\\\<literal><green>, yet no green');
`

Just my early morning ramblings...

**Comment by haxiomic** [comment]
I see what you mean on escaping the escape character

I think that's a rare enough use case that I'll leave it be for now, maybe later I could go the html way and use `&lt;` for <
